[package]
name = "ladle"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.11.4", features = ['json'] }
serde = { version = "1.0.126", features = ['derive'] }
serde_json = {version = "~1.0.89"}
unidecode = "0.3.0"
log = "0.4.6"
